### ISSUE TITLE
Help updates for 3.3.0

### ISSUE THREAD

**Issue by juddey** [seven1m/onebody-help#31]
This issue is simply a scratch pad to document items I'd like to add in the next release of the help. It saves it from being on my whiteboard at home :smile: 
- Add translated languages and images of national flags to front page.
- Move the note on the front page about the term "member" somewhere else.
- fix the note tag in the "pages" article.
- Remove the notes feature (I think just on the table of the admin roles page)
- Add note for mailgun about receiving an email when you reach your limit 
- Document difference between site and a community? (there really isn't one :)

**Comment by x-light** [comment]
Add Documentation for Reporting Engine.
Possible examples:
- [ ] Names and Addresses for mail merge
- [ ] Small Groups, their members, and their email addresses
- [ ] Names of those under a certain age

**Comment by x-light** [comment]
Clarify the purpose of the Group Adminstration page. See churchio/onebody#494
